// projects/demos/vue/src/App.vue
<script setup lang="ts">
  import '@elements/elements/app-header/define.js';
  import '@elements/elements/button/define.js';
  import '@elements/elements/breadcrumb/define.js';
  import '@elements/elements/drawer/define.js';
  import '@elements/elements/menu/define.js';
</script>

<template>
  <mlv-app-header>
    <mlv-logo></mlv-logo>
    <h2 slot="title">Elements</h2>
    <mlv-button slot="nav-items" selected=" "><a href="/elements/demos/buildless/">Demos</a></mlv-button>
    <mlv-button slot="nav-items"><a href="https://NVIDIA.github.io/elements/api/" target="_blank">API</a></mlv-button>
    <mlv-button slot="nav-items"><a href="https://github.com/NVIDIA/elements/" target="_blank">Gitlab</a></mlv-button>
    <mlv-button slot="nav-items"><a href="https://elements-stage.nvidia.com/ui/elements-playground" target="_blank">Playground</a></mlv-button>
    <mlv-icon-button icon-name="switch-apps" slot="nav-actions"></mlv-icon-button>
  </mlv-app-header>
  <div mlv-layout="row" style="height: 100%">
    <mlv-drawer .inline="true" size="sm" style="--top: 48px; display: block">
      <mlv-drawer-header>
        <div mlv-layout="row gap:xs align:vertical-center">Demos</div>
      </mlv-drawer-header>
      <mlv-drawer-content>
        <mlv-menu>
          <mlv-menu-item>
            <a href="/elements/demos/buildless/">
              <img src="/javascript.svg" width="18px" height="18px" alt="javascript logo" />
              Buildless
            </a>
          </mlv-menu-item>
          <mlv-menu-item>
            <a href="/elements/demos/typescript/">
              <img src="/typescript.svg" width="18px" height="18px" alt="typescript logo" />
              TypeScript
            </a>
          </mlv-menu-item>
          <mlv-menu-item>
            <a href="/elements/demos/angular/">
              <img src="/angular.svg" width="18px" height="18px" alt="angular logo" />
              Angular
            </a>
          </mlv-menu-item>
          <mlv-menu-item current="page">
            <a href="/elements/demos/vue/">
              <img src="/vue.svg" width="18px" height="18px" alt="vue logo" />
              Vue
            </a>
          </mlv-menu-item>
          <mlv-menu-item>
            <a href="/elements/demos/react/">
              <img src="/react.svg" width="18px" height="18px" alt="react logo" />
              React
            </a>
          </mlv-menu-item>
          <mlv-menu-item>
            <mlv-icon name="template"></mlv-icon>
            <a href="/elements/demos/mpa/">MPA</a>
          </mlv-menu-item>
        </mlv-menu>
      </mlv-drawer-content>
    </mlv-drawer>
    <main mlv-layout="column gap:lg pad-x:xl pad-y:md align:stretch">
      <mlv-breadcrumb>
        <mlv-button><a href="/elements/demos/buildless/">Elements</a></mlv-button>
        <mlv-button><a href="/elements/demos/buildless/" target="_self">Demos</a></mlv-button>
        <span>Vue</span>
      </mlv-breadcrumb>
      <h1 mlv-text="heading xl">Vue</h1>
      <p mlv-text="body">A simple starter using Elements and Vue.</p>
      <ul mlv-text="list" mlv-layout="column gap:xs">
        <li><a mlv-text="link" target="_blank" href="https://github.com/NVIDIA/elements/-/tree/main/projects/demos/vue">Source</a></li>
        <li><a mlv-text="link" target="_blank" href="https://NVIDIA.github.io/elements/api/?path=/docs/integrations-vue--docs">Documentation</a></li>
      </ul>
    </main>
  </div>
</template>

<style scoped>

</style>

// projects/demos/react/src/App.tsx
import React from 'react';
import { MlvAppHeader } from '@elements/elements-react/app-header';
import { MlvButton } from '@elements/elements-react/button';
import { MlvIconButton } from '@elements/elements-react/icon-button';
import { MlvLogo } from '@elements/elements-react/logo';
import { MlvBreadcrumb } from '@elements/elements-react/breadcrumb';
import { MlvDrawer, MlvDrawerContent, MlvDrawerHeader } from '@elements/elements-react/drawer';
import { MlvMenu, MlvMenuItem } from '@elements/elements-react/menu';

function App() {
  return (
    <div>
      <MlvAppHeader>
        <MlvLogo></MlvLogo>
        <h2 slot="title">Elements</h2>
        <MlvButton slot="nav-items" selected><a href="/demos/buildless/">Demos</a></MlvButton>
        <MlvButton slot="nav-items"><a href="https://NVIDIA.github.io/elements/api/" target="_blank">API</a></MlvButton>
        <MlvButton slot="nav-items"><a href="https://github.com/NVIDIA/elements/" target="_blank">Gitlab</a></MlvButton>
        <MlvButton slot="nav-items"><a href="https://elements-stage.nvidia.com/ui/elements-playground" target="_blank">Playground</a></MlvButton>
        <MlvIconButton icon-name="switch-apps" slot="nav-actions"></MlvIconButton>
      </MlvAppHeader>
      <div mlv-layout="row" style={{ height: '100%' }}>
        <MlvDrawer inline size="sm" style={{ '--top': '48px', display: 'block' }}>
          <MlvDrawerHeader>
            <div mlv-layout="row gap:xs align:vertical-center">Demos</div>
          </MlvDrawerHeader>
          <MlvDrawerContent>
            <MlvMenu>
              <MlvMenuItem>
                <a href="/demos/buildless/">
                  <img src="/demos/react/javascript.svg" width="18px" height="18px" alt="javascript logo" />
                  Buildless
                </a>
              </MlvMenuItem>
              <MlvMenuItem>
                <a href="/demos/typescript/">
                  <img src="/demos/react/typescript.svg" width="18px" height="18px" alt="typescript logo" />
                  TypeScript
                </a>
              </MlvMenuItem>
              <MlvMenuItem>
                <a href="/demos/angular/">
                  <img src="/demos/react/angular.svg" width="18px" height="18px" alt="angular logo" />
                  Angular
                </a>
              </MlvMenuItem>
              <MlvMenuItem>
                <a href="/demos/vue/">
                  <img src="/demos/react/vue.svg" width="18px" height="18px" alt="vue logo" />
                  Vue
                </a>
              </MlvMenuItem>
              <MlvMenuItem current="page">
                <a href="/demos/react/">
                  <img src="/demos/react/react.svg" width="18px" height="18px" alt="react logo" />
                  React
                </a>
              </MlvMenuItem>
              <MlvMenuItem>
                <mlv-icon name="template"></mlv-icon>
                <a href="/demos/mpa/">MPA</a>
              </MlvMenuItem>
            </MlvMenu>
          </MlvDrawerContent>
        </MlvDrawer>
        <main mlv-layout="column gap:lg pad-x:xl pad-y:md align:stretch">
          <MlvBreadcrumb>
            <MlvButton><a href="/demos/buildless/">Elements</a></MlvButton>
            <MlvButton><a href="/demos/buildless/" target="_self">Demos</a></MlvButton>
            <span>React</span>
          </MlvBreadcrumb>
          <h1 mlv-text="heading xl">React</h1>
          <p mlv-text="body">A simple starter using Elements and React.</p>
          <ul mlv-text="list" mlv-layout="column gap:xs">
            <li><a mlv-text="link" target="_blank" href="https://github.com/NVIDIA/elements/-/tree/main/projects/demos/react">Source</a></li>
            <li><a mlv-text="link" target="_blank" href="https://NVIDIA.github.io/elements/api/?path=/docs/integrations-react--docs">Documentation</a></li>
          </ul>
        </main>
      </div>
    </div>
  );
}

export default App;
